name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }} build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
      - name: Run tests
        run: coverage run src/test.py
      - name: Tests report
        run: coverage report

      #- name: Hello world action step
      #  id: hello
      #  uses: ozada/test-action@v1
      #  with:
      #    who-to-greet: 'Joe Dow'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"